version: '3'
services:
  DBForStudentApplication:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: StudentDB
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  student-application:
    image: demo-student-application
    depends_on:
      - DBForStudentApplication
    ports:
      - "8080:8080"